from .price_comparison import PriceComparison
from .news import News
from .favourite import Favourite
from .checkout import Checkout
from .cart import Cart
from .notification import Notification
from .profile import Profile
from .product import Product
from .register import Register
from .login import Login
